### ISSUE TITLE
Can’t set custom pictures…

### ISSUE THREAD

**Issue by ArmasF31** [E-boi/custom-rpc#6]
I can't seem to set custom pictures, even though the ID is correct.

**Comment by Mr-Resetti** [comment]
ever figure this out?

**Comment by xNasuni** [comment]
you made a application and added the images to the art assets right you should change the name of the file to whatever you want then when you add it to that the key for that image will be the name of that file and then in the settings (powercord plugin settings) you type in the name of the image key in the 'LARGE IMAGE', and 'SMALL IMAGE' fields instead of links.

**Comment by iCrayix** [comment]
> 
> 
> you made a application and added the images to the art assets right you should change the name of the file to whatever you want then when you add it to that the key for that image will be the name of that file and then in the settings (powercord plugin settings) you type in the name of the image key in the 'LARGE IMAGE', and 'SMALL IMAGE' fields instead of links.

Can u explain to me please?
I dont understand where to put the images

**Comment by E-boi** [comment]
You can look at the bottom of the settings page for help.

**Comment by E-boi** [comment]
Hey small update, I have updated the plugin to have dropdowns for large and small images if the client id is correct all you would need to do is select the image.

**Comment by rollingmoai** [comment]
> Hey small update, I have updated the plugin to have dropdowns for large and small images if the client id is correct all you would need to do is select the image.

@E-boi How do I set it to none though? I have selected one and I am stuck with an image now.

**Comment by E-boi** [comment]
> @E-boi How do I set it to none though? I have selected one and I am stuck with an image now.

oh I didn't think about that.

**Comment by E-boi** [comment]
ok pushed a small update for this.
