### ISSUE TITLE
Dropdown on Large and Small Images

### ISSUE THREAD

**Issue by rollingmoai** [E-boi/custom-rpc#7]
Make large image and small image a dropdown instead of a text field having to know the name of the keys much like in [DiscordRPCMaker](https://github.com/ThatOneCalculator/DiscordRPCMaker).

![example](https://user-images.githubusercontent.com/75471378/127323046-3c8d8887-c7bd-4887-bc73-3474b5ecc372.png)

**Comment by E-boi** [comment]
great suggestion! I'm gonna try to implement this.

**Comment by rollingmoai** [comment]
@E-boi Thanks, but I can't seem to deselect it once I have selected one. How do I set the key to none?
