### ISSUE TITLE
Settings panel does not work

### ISSUE THREAD

**Issue by BotterManTingGoes** [E-boi/custom-rpc#9]
![image](https://user-images.githubusercontent.com/89749332/148922665-8bd4af90-5d5b-4d60-8c4f-2bcb0ebe3e50.png)

upon clicking on custom RPC in settings panel, this error/traceback just appears

**Comment by SheepCommander** [comment]
confirm

**Comment by E-boi** [comment]
sorry for the delay, settings should be fixed now
